export const theme = {
  font: {},
  color: {
    blackOpa: 'rgba(0, 0, 0, 0.3)',
    white: '#ffffff',
    whiteTransparent: 'rgba(0,0,0, 0)',
    black: '#000000',
    medium: '#999999',
    gray: '#DBDBDB',
    lightGray: '#F7F7F7',
    red: '#F24848',
  },
  size: {
    medium: '1.5rem',
    normal: '1.25rem',
    defaulish: '1rem',
    default: '0.875rem',
    small: '0.75rem',
  },
  radius: {
    bigger: '1.25rem',
    big: '1rem',
    medium: '0.625rem',
    default: '0.25rem',
  },
  boxShadow: {
    medium: '0 0.1875rem 1.25rem rgba(0, 0, 0, 0.3)',
    default: '0 0.1875rem 0.375rem rgba(0, 0, 0, 0.3)',
  },
  textShadow: {},
  images: {
    logo: '/images/logo.svg',
    circle: '/images/circle.svg',
    search: '/images/search.svg',
    weight: '/images/weight.svg',
    generate: '/images/generate.svg',
    history: '/images/history.svg',
    rename: '/images/rename.svg',
    delete: '/images/delete.svg',
    upload: '/images/upload-cloud.svg',
    file: '/images/file.svg',
    chevronLeft: '/images/chevron-left.svg',
    chevronRight: '/images/chevron-right.svg',
    checkCircle: '/images/check-circle.svg',
    folderClosed: '/images/folder-closed.svg',
    checkpoint: '/images/checkpoint.svg',
    branch: '/images/branch.svg',
    sample: '/images/sample.svg',
    arrowDown: '/images/arrow-down-circle.svg',
    arrowDownGray: '/images/arrow-down-circle-gray.svg',
  },
  screenWidth: {
    screen: '63rem',
    tablet: '42rem',
  },
}
